apiVersion: v1
kind: Service
metadata:
  name: {{ include "samba-server.fullname" . }}
  labels:
    {{- include "samba-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: smbd
  selector:
    {{- include "samba-server.selectorLabels" . | nindent 4 }}
